repos:
  - repo: local
    hooks:
      - id: run-all
        name: Run all validation checks
        entry: bash hooks/run-all.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]
