name: "Pre-commit Hooks Suite"
description: "Run individual quality/security checks from hooks/*.sh with per-check toggles"
author: "calebsargeant"
branding:
  icon: "shield"
  color: "blue"
inputs:
  stage:
    description: "Hook stage to run (pre-commit or pre-push)"
    required: false
    default: "pre-commit"
  fail_on_high_severity:
    description: "Fail when high severity security issues are found"
    required: false
    default: "true"
  fail_on_medium_severity:
    description: "Fail when medium severity security issues are found"
    required: false
    default: "false"
  run_security:
    description: "Run security-check.sh"
    required: false
    default: "true"
  run_file_quality:
    description: "Run file-quality.sh"
    required: false
    default: "true"
  run_python:
    description: "Run python-quality.sh"
    required: false
    default: "true"
  run_javascript:
    description: "Run javascript-quality.sh"
    required: false
    default: "true"
  run_terraform:
    description: "Run terraform-quality.sh"
    required: false
    default: "true"
  run_docker:
    description: "Run docker-security.sh"
    required: false
    default: "true"
  run_license:
    description: "Run license-check.sh"
    required: false
    default: "false"
  run_code_metrics:
    description: "Run code-metrics.sh"
    required: false
    default: "false"
  run_performance:
    description: "Run performance-check.sh"
    required: false
    default: "false"
  run_precommit_basic:
    description: "Run pre-commit-basic.sh"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: 🧹 File Quality
      if: ${{ inputs.run_file_quality == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/file-quality.sh"

    - name: 🛡️ Security Scan
      if: ${{ inputs.run_security == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
        FAIL_ON_HIGH_SEVERITY: ${{ inputs.fail_on_high_severity }}
        FAIL_ON_MEDIUM_SEVERITY: ${{ inputs.fail_on_medium_severity }}
      run: |
        bash "${{ github.action_path }}/hooks/security-check.sh"

    - name: 🐍 Python Quality
      if: ${{ inputs.run_python == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/python-quality.sh"

    - name: 📋 JavaScript Quality
      if: ${{ inputs.run_javascript == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/javascript-quality.sh"

    - name: 🏗️ Terraform Validation
      if: ${{ inputs.run_terraform == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/terraform-quality.sh"

    - name: 🐋 Docker Security
      if: ${{ inputs.run_docker == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/docker-security.sh"

    - name: ⚖️ License Compliance
      if: ${{ inputs.run_license == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/license-check.sh"

    - name: 📊 Code Metrics
      if: ${{ inputs.run_code_metrics == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/code-metrics.sh"

    - name: ⚡ Performance Check
      if: ${{ inputs.run_performance == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/performance-check.sh"

    - name: 🔧 Pre-commit Basic Hygiene
      if: ${{ inputs.run_precommit_basic == 'true' }}
      shell: bash
      env:
        PRE_COMMIT_STAGE: ${{ inputs.stage }}
      run: |
        bash "${{ github.action_path }}/hooks/pre-commit-basic.sh"
