name: Merge Gate CI
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  setup-actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Build actionlint binary
        run: |
          set -Eeuo pipefail
          mkdir -p bin
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download/actionlint.bash | bash -s -- -b bin
      - name: Upload actionlint
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: actionlint-bin
          path: bin/actionlint

  setup-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Download gitleaks
        run: |
          set -Eeuo pipefail
          mkdir -p bin
          GL_VERSION=8.18.3
          curl -sSL -o bin/gitleaks.tar.gz "https://github.com/gitleaks/gitleaks/releases/download/v${GL_VERSION}/gitleaks_${GL_VERSION}_linux_x64.tar.gz"
          tar -C bin -xzf bin/gitleaks.tar.gz gitleaks
          rm -f bin/gitleaks.tar.gz
      - name: Upload gitleaks
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: gitleaks-bin
          path: bin/gitleaks

  setup-kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Download kubeconform
        run: |
          set -Eeuo pipefail
          mkdir -p bin
          KCF_VERSION=0.6.7
          curl -sSL -o bin/kubeconform.tar.gz "https://github.com/yannh/kubeconform/releases/download/v${KCF_VERSION}/kubeconform-linux-amd64.tar.gz"
          tar -C bin -xzf bin/kubeconform.tar.gz kubeconform
          rm -f bin/kubeconform.tar.gz
      - name: Upload kubeconform
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: kubeconform-bin
          path: bin/kubeconform

  setup-tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Download tfsec
        run: |
          set -Eeuo pipefail
          mkdir -p bin
          curl -sSfL -o bin/tfsec https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x bin/tfsec
      - name: Upload tfsec
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: tfsec-bin
          path: bin/tfsec

  setup-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Download trivy
        run: |
          set -Eeuo pipefail
          mkdir -p bin
          TV=v0.52.3
          curl -sSL -o trivy.tar.gz "https://github.com/aquasecurity/trivy/releases/download/${TV}/trivy_${TV#v}_Linux-64bit.tar.gz"
          tar -xzf trivy.tar.gz trivy
          mv trivy bin/
          rm -f trivy.tar.gz
      - name: Upload trivy
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: trivy-bin
          path: bin/trivy

  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Create venv and install tools
        run: |
          set -Eeuo pipefail
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install pip-audit checkov yamllint
          deactivate
          tar -czf python-venv.tar.gz .venv
      - name: Upload python venv
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: python-venv
          path: python-venv.tar.gz

  merge-gate:
    runs-on: ubuntu-latest
    needs:
      - setup-actionlint
      - setup-gitleaks
      - setup-kubeconform
      - setup-tfsec
      - setup-trivy
      - setup-python
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'

      - name: Download tools
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: actionlint-bin
          path: bin
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: gitleaks-bin
          path: bin
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: kubeconform-bin
          path: bin
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: tfsec-bin
          path: bin
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: trivy-bin
          path: bin

      - name: Download python venv
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: python-venv
          path: .
      - name: Extract python venv
        run: |
          tar -xzf python-venv.tar.gz
          echo "$PWD/bin" >> "$GITHUB_PATH"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false

      - name: Setup Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@2ba527d4d055ab63514ba50a99456fc35684947f # v2.1.0

      - name: Run merge gate checks
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          VIRTUAL_ENV: ${{ github.workspace }}/.venv
          PATH: ${{ github.workspace }}/.venv/bin:${{ github.workspace }}/bin:${{ env.PATH }}
        run: bash hooks/ci-merge-gate.sh
