name: Merge Gate CI
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  merge-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false

      - name: Setup Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@2ba527d4d055ab63514ba50a99456fc35684947f # v2.1.0

      - name: Install actionlint
        run: |
          set -Eeuo pipefail
          mkdir -p bin
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download/actionlint.bash | bash -s -- -b bin
          echo "$PWD/bin" >> "$GITHUB_PATH"

      - name: Install gitleaks
        run: |
          set -Eeuo pipefail
          GL_VERSION=8.18.3
          curl -sSL -o bin/gitleaks.tar.gz "https://github.com/gitleaks/gitleaks/releases/download/v${GL_VERSION}/gitleaks_${GL_VERSION}_linux_x64.tar.gz"
          tar -C bin -xzf bin/gitleaks.tar.gz gitleaks
          rm -f bin/gitleaks.tar.gz

      - name: Install kubeconform
        run: |
          set -Eeuo pipefail
          KCF_VERSION=0.6.7
          curl -sSL -o bin/kubeconform.tar.gz "https://github.com/yannh/kubeconform/releases/download/v${KCF_VERSION}/kubeconform-linux-amd64.tar.gz"
          tar -C bin -xzf bin/kubeconform.tar.gz kubeconform
          rm -f bin/kubeconform.tar.gz

      - name: Install tfsec
        run: |
          set -Eeuo pipefail
          curl -sSfL -o bin/tfsec https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x bin/tfsec

      - name: Install trivy
        run: |
          set -Eeuo pipefail
          TV=v0.52.3
          curl -sSL -o trivy.tar.gz "https://github.com/aquasecurity/trivy/releases/download/${TV}/trivy_${TV#v}_Linux-64bit.tar.gz"
          tar -xzf trivy.tar.gz trivy
          mv trivy bin/
          rm -f trivy.tar.gz

      - name: Install python security tools
        run: |
          set -Eeuo pipefail
          sudo apt-get update
          sudo apt-get install -y yamllint python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pip-audit checkov

      - name: Run merge gate checks
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          export PATH="$PWD/bin:$PATH"
          bash hooks/ci-merge-gate.sh
