name: Run Pre-commit Hooks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  precommit:
    uses: calebsargeant/reusable-workflows/.github/workflows/hooks-ci.yml@latest
    with:
      stage: pre-commit
      fail_on_high_severity: true
      fail_on_medium_severity: false
      run_all: true
