#name: Run Pre-commit Hooks
#
#on:
#  push:
#    branches: [main]
#  pull_request:
#
#jobs:
#  precommit:
#    uses: calebsargeant/reusable-workflows/.github/workflows/hooks-ci.yml@main
#    with:
#      stage: pre-commit
#      fail_on_high_severity: true
#      fail_on_medium_severity: false
#      run_security: true
#      run_file_quality: true
#      run_python: true
#      run_javascript: true
#      run_terraform: false
#      run_docker: true
#      run_license: false
#      run_code_metrics: false
#      run_performance: false
#      run_precommit_basic: false