name: CI
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  merge-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false

      - name: Setup Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@2ba527d4d055ab63514ba50a99456fc35684947f # v2.1.0

      - name: Setup actionlint
        uses: raven-actions/actionlint@3a24062651993d40fed1019b58ac6fbdfbf276cc # v2.0.1

      - name: Setup tfsec
        uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # v1.0.3

      - name: Setup trivy
        uses: aquasecurity/setup-trivy@e6c2c5e321ed9123bda567646e2f96565e34abe1 # v0.2.4

      - name: Setup gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        with:
          source: '.'
          args: '--no-banner --redact'
        continue-on-error: true

      - name: Setup kubeconform
        run: |
          set -Eeuo pipefail
          KCF_VERSION=$(curl -sSL https://api.github.com/repos/yannh/kubeconform/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          curl -sSL -o kubeconform.tar.gz "https://github.com/yannh/kubeconform/releases/download/v${KCF_VERSION}/kubeconform-linux-amd64.tar.gz"
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/
          rm -f kubeconform.tar.gz

      - name: Setup yamllint and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint python3-pip

      - name: Restore python cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .venv
          key: merge-gate-venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt', '.python-version') }}-v1
          restore-keys: merge-gate-venv-${{ runner.os }}

      - name: Setup python venv
        run: |
          set -Eeuo pipefail
          if [[ ! -d .venv ]]; then
            python3 -m venv .venv
          fi
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install pip-audit checkov
          deactivate
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Run merge gate checks
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          export PATH="${{ github.workspace }}/.venv/bin:/usr/local/bin:/usr/bin:$PATH"
          bash hooks/ci-merge-gate.sh
