name: Run Pre-commit Hooks
permissions:
  contents: read

on:
  pull_request:

jobs:
  precommit:
    uses: calebsargeant/reusable-workflows/.github/workflows/hooks-ci.yml@1a02100deff6fe75e42a5ab0b62ada6a58820495 # v1.0.2
    with:
      stage: pre-commit
      fail_on_high_severity: true
      fail_on_medium_severity: false
      run_all: true
